### ISSUE TITLE
PUSH_ACK where PULL_ACK expected

### ISSUE THREAD

**Issue by arjanvanderoest** [TheThingsNetwork/croft#11]
I might be wrong here but to me it seems the TTN gateway server is responding wrong to my PULL_DATA requests sent by my Kerlink, causing:

INFO: [down] the last 3 PULL_DATA were not ACKed, exiting application

In the screenshots you can see the PULL_DATA being sent and answered with a PUSH_ACK (0x01) where 0x04 is expected.

<img width="815" alt="screen shot 2015-11-24 at 18 52 04" src="https://cloud.githubusercontent.com/assets/10079802/11383594/8ce7af3a-9309-11e5-8762-6b37d7712676.png">

<img width="810" alt="screen shot 2015-11-24 at 18 52 31" src="https://cloud.githubusercontent.com/assets/10079802/11383600/95f62bd8-9309-11e5-861c-7cc3c5c87898.png">

**Comment by arjanvanderoest** [comment]
I see you are now answering 0x02 with 0x03, according to the Semtech documentation this is PULL_RESP, not PULL_ACK. Imho this is invalid too. The PULL_REQ (0x02) should (imho) be answered with a PULL_ACK (0x04).

**Comment by johanstokking** [comment]
Hmm wrong iotas. Thanks for prompt response, will fix.





On Mon, Nov 30, 2015 at 12:41 PM -0800, "Arjan van der Oest" <notifications@github.com<mailto:notifications@github.com>> wrote:


I see you are now answering 0x02 with 0x03, according to the Semtech documentation this is PULL_RESP, not PULL_ACK. Imho this is invalid too. The PULL_REQ (0x02) should (imho) be answered with a PULL_ACK (0x04).

-

**Comment by johanstokking** [comment]
OK fixed now, thanks
