### ISSUE TITLE
rssi missing in packages sent by croft

### ISSUE THREAD

**Issue by matthiaszimmermann** [TheThingsNetwork/croft#12]
please add the signal strength indicator data to the packages sent to jolie this helps to better understand gateway coverage measurements.

**proposal**: as the croft lora.RXPK seems to have an Rssi attribute it should be possible to include this in in croft server method convertRXPK. 

**background/motivation**: yesterday @gonzalocasas and me were testing things nodes in zurich with two things nodes. one with a proper antenna and one BETA v1 node. 

while packages of the first node were received and displayed on the django rest api http://thethingsnetwork.org/api/v0/nodes/<nodeid>/ we did not have any luck with thethings uno and its onboard antenna. on mqtt (croft.thethings.girovito.nl:1883) singal strength information also seems missing

having the singal strenght information available in the rest api and on mqtt would help to get a better understanding regading combinations of setups and related ranges.

**Comment by bitmorse** [comment]
+1

**Comment by nielsoo** [comment]
+1

**Comment by matthiaszimmermann** [comment]
checked today, and it's working. thanks much!
