### ISSUE TITLE
croft parses time incorrect

### ISSUE THREAD

**Issue by ernstdevreede** [TheThingsNetwork/croft#16]
It looks like croft incorrectly tries to parse timestamps in "stat" and/or "rxpk" packets as rfc822 ("02 Jan 06 15:04 MST") instead of using RFC3339 or something ike that ("2016-01-04 21:04:04 GMT").

Current time seems to be used in this case, which is (almost) correct anyway.

This is shown in the logfile of croft (version installed from GitHub on Jan 3).

**Comment by johanstokking** [comment]
Thanks @ernstdevreede, it's indeed the stat message. It's a weird format and the parsing needs to be adjusted to this. As a fallback, the current time is used.

**Comment by ernstdevreede** [comment]
It also seems that sometimes 0001-01-01T00:00:00Z is the result of the (failed parsing), so failing to parse the time does not (always) seem to fallback to the currrent time. Or this might be caused by otherwise malformed packets (I see this using the single_packet_gateway).

[Because of packets being sorted by time in the API these packets "from the year 0001" are difficult to find at all in the API]

**Comment by johanstokking** [comment]
Are you sure this is the gateway status? Because it seems that you talk about packet time. If so, please file a separate issue.
